apiVersion: apps/v1
kind: Deployment
metadata:
  name: care-user-medicine-inventory-deployment
  labels:
    app: care-user-medicine-inventory
spec:
  replicas: 1
  selector:
    matchLabels:
      app: care-user-medicine-inventory
  template:
    metadata:
      labels:
        app: care-user-medicine-inventory
    spec:
      containers:
        - name: care-user-medicine-inventory
          image: victoriafongacr.azurecr.io/care-user-medicine-inventory:v4
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Staging
          resources:
            requests:
              cpu: 250m
            limits:
              cpu: 500m
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: care-user-medicine-inventory-hpa
spec:
  maxReplicas: 3 # define max replica count
  minReplicas: 1 # define min replica count
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: care-user-medicine-inventory-deployment
  targetCPUUtilizationPercentage: 50 # target CPU utilization
