apiVersion: apps/v1
kind: Deployment
metadata:
  name: care-medicine-inventory-deployment
  labels:
    app: care-medicine-inventory
spec:
  replicas: 1
  selector:
    matchLabels:
      app: care-medicine-inventory
  template:
    metadata:
      labels:
        app: care-medicine-inventory
    spec:
      containers:
        - name: care-medicine-inventory
          image: vcaf/care-medicine-inventory:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Staging
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
