version: "3.8"

services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - 27017:27017
    volumes:
      - mongodbdata:/data/db

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
    #first port is to consume messages from RabbitMQ
      - 5672:5672
    #second port is to locate to the RabbitMQ portal
      - 15672:15672
    volumes:
      - rabbitmqdata:/var/lib/rabbitmq
    hostname: rabbitmq

  frontend:
    image: care-frontend:latest
    container_name: "frontend"
    depends_on:
      backend-medicine:
        condition: service_started
      backend-user-medicine:
        condition: service_started
    ports:
      - 3030:3030
    expose:
      - "3030"

  backend-medicine:
    image: care-medicine-inventory:latest
    container_name: "backend-medicine"
    ports:
      - 5001:80
    expose:
      - "5001"
    environment:
      ASPNETCORE_ENVIRONMENT: Staging
    links:
      - mongo

  backend-user-medicine:
    image: care-user-medicine-inventory:latest
    container_name: "backend-user-medicine"
    ports:
      - 5005:80
    expose:
      - "5005"
    environment:
      ASPNETCORE_ENVIRONMENT: Staging
    links:
      - mongo

volumes:
  mongodbdata:
  rabbitmqdata: