apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
    kompose.service.type: LoadBalancer
    kompose.version: 1.27.0 (b0ed6a2c9)
  creationTimestamp: null
  labels:
    io.kompose.service: care-user-medicine-inventory-tcp
  name: care-user-medicine-inventory-tcp
spec:
  ports:
    - name: "5005"
      port: 5005
      targetPort: 80
  selector:
    io.kompose.service: care-user-medicine-inventory
  type: LoadBalancer
status:
  loadBalancer: {}
